### ISSUE TITLE
docs: 이슈 템플릿 생성

### ISSUE THREAD

**Issue by jae-hwan-kim** [Just-Swim-service/Just-Swim-FE#1]
# Issue
이슈를 위한 템플릿 생성

# Description
개발 과정에서 원활한 소통을 위해 이슈 템플릿을 생성하여, 사용하도록 합니다.
Git Flow 의 브랜치와 같은 구조로 템플릿을 구성합니다.

# Todo
- [ ] main 템플릿 생성 - 배포 위한 이슈
- [ ] develop 템플릿 생성 - 다른 브랜치에서 구현된 것을 모으는 이슈
- [ ] release 템플릿 생성 - 배포 전 테스트 및 QA 를 위한 이슈
- [ ] feature 템플릿 생성 - 기능을 위한 이슈
- [ ] fix 템플릿 생성 - develop 에 수정사항이 있을 때를 위한 이유
- [ ] hotfix 템플릿 생성 - 배포 후 빠르게 수정하기 위한 이슈
- [ ] refactor 템플릿 생성 - 리팩토링을 위한 브랜치
- [ ] docs 템플릿 생성 - 문서를 위한 이슈
